# Generated by Django 2.2 on 2021-01-23 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20210123_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
    ]
