# Generated by Django 2.2 on 2021-01-23 11:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210123_0543'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сообщения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Users', verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['pub_date'],
            },
        ),
    ]
