# Generated by Django 2.2 on 2021-01-23 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend',
            field=models.ManyToManyField(default='', related_name='add_friend', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
